include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    # avoid_function_literals_in_foreach_calls: false
    use_setters_to_change_properties: false
    # join_return_with_assignment: false
    avoid_relative_lib_imports: false